package modelo;
// Generated 28/11/2012 17:20:18 by Hibernate Tools 3.2.1.GA



/**
 * Uva generated by hbm2java
 */
public class Uva  implements java.io.Serializable {


     private Integer iduva;
     private String nombreUva;
     private String colorUva;

    public Uva() {
    }

	
    public Uva(String nombreUva) {
        this.nombreUva = nombreUva;
    }
    public Uva(String nombreUva, String colorUva) {
       this.nombreUva = nombreUva;
       this.colorUva = colorUva;
    }
   
    public Integer getIduva() {
        return this.iduva;
    }
    
    public void setIduva(Integer iduva) {
        this.iduva = iduva;
    }
    public String getNombreUva() {
        return this.nombreUva;
    }
    
    public void setNombreUva(String nombreUva) {
        this.nombreUva = nombreUva;
    }
    public String getColorUva() {
        return this.colorUva;
    }
    
    public void setColorUva(String colorUva) {
        this.colorUva = colorUva;
    }




}


